#!/usr/bin/env python3
"""Draws the SignoVoice app icon so it is identical to the in-app logo (lib/shared/widgets/brand.dart):
indigo tile + the white Material `sign_language_rounded` glyph (two hands) + cyan and teal dots.

The glyph outline is read from Flutter's own MaterialIcons font, so vector and PNG outputs match the in-app mark exactly.
Writes: res/drawable/ic_launcher_foreground.xml, splash_logo.xml, ic_launcher_monochrome.xml, legacy mipmap PNGs, assets/store/play_icon_512.png.
Requires:  pip install pillow fonttools
Usage:     python3 tools/icons/generate_icons.py [/path/to/MaterialIcons-Regular.otf]
"""
import os
import sys

from fontTools.pens.basePen import BasePen
from fontTools.ttLib import TTFont
from PIL import Image, ImageDraw, ImageFont

CODEPOINT = 0xF081B  # Icons.sign_language_rounded
FONT = (sys.argv[1] if len(sys.argv) > 1 else
        '/opt/flutter-sdk/flutter/bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf')
INDIGO, WHITE, CYAN, TEAL = (0x31, 0x57, 0xD5, 255), (255, 255, 255, 255), (0x22, 0xC7, 0xE8, 255), (0x12, 0xA5, 0x94, 255)
SS = 4

# BrandMark proportions (fractions of the tile size S): glyph 0.56; cyan dot d=0.16 at right/top 0.1; teal dot d=0.11 at right 0.2 / bottom 0.14.
GLYPH = 0.56
DOTS = [  # (center x, center y, radius, color) as fractions of S, y from top
    (1 - 0.1 - 0.08, 0.1 + 0.08, 0.08, CYAN),
    (1 - 0.2 - 0.055, 1 - 0.14 - 0.055, 0.055, TEAL),
]


class _Path(BasePen):
    """Collects the glyph as Android pathData in a box: (x0,y0) top-left, `em` size, y flipped."""

    def __init__(self, gs, em_units, x0, y0, em):
        super().__init__(gs)
        self.k, self.x0, self.y0, self.em_units, self.em, self.out = em / em_units, x0, y0, em_units, em, []

    def _p(self, pt):
        return f'{self.x0 + pt[0] * self.k:.2f},{self.y0 + (self.em_units - pt[1]) * self.k:.2f}'

    def _moveTo(self, pt): self.out.append('M' + self._p(pt))
    def _lineTo(self, pt): self.out.append('L' + self._p(pt))
    def _curveToOne(self, a, b, c): self.out.append('C' + ' '.join(self._p(p) for p in (a, b, c)))
    def _qCurveToOne(self, a, b): self.out.append('Q' + ' '.join(self._p(p) for p in (a, b)))
    def _closePath(self): self.out.append('Z')


def glyph_path(tile_origin, tile):
    f = TTFont(FONT)
    name = f.getBestCmap()[CODEPOINT]
    gs = f.getGlyphSet()
    em = GLYPH * tile
    p = _Path(gs, f['head'].unitsPerEm, tile_origin + (tile - em) / 2, tile_origin + (tile - em) / 2, em)
    gs[name].draw(p)
    return ''.join(p.out)


def circle(cx, cy, r):
    return f'M{cx - r:.2f},{cy:.2f} A{r:.2f},{r:.2f} 0 1 1 {cx + r:.2f},{cy:.2f} A{r:.2f},{r:.2f} 0 1 1 {cx - r:.2f},{cy:.2f} Z'


def write_vectors(res):
    # Adaptive icon: full-bleed indigo background + this foreground, mark sized to sit inside the 66dp safe zone.
    tile, origin = 76.0, 16.0
    d = os.path.join(res, 'drawable')
    gp = glyph_path(origin, tile)
    dots = ''.join(
        f'    <path android:fillColor="#{c[0]:02X}{c[1]:02X}{c[2]:02X}" android:pathData="{circle(origin + fx * tile, origin + fy * tile, r * tile)}" />\n'
        for fx, fy, r, c in DOTS)
    head = ('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/icons/generate_icons.py: the in-app logo '
            '(Material sign_language_rounded + two dots). Do not edit by hand. -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n    android:width="108dp"\n    android:height="108dp"\n'
            '    android:viewportWidth="108"\n    android:viewportHeight="108">\n')
    open(os.path.join(d, 'ic_launcher_foreground.xml'), 'w').write(
        head + f'    <path android:fillColor="#FFFFFF" android:pathData="{gp}" />\n' + dots + '</vector>\n')
    open(os.path.join(d, 'ic_launcher_monochrome.xml'), 'w').write(
        head.replace('Generated', 'Single-colour (Android 13+ themed icon). Generated') +
        f'    <path android:fillColor="#FFFFFF" android:pathData="{gp}" />\n</vector>\n')


def write_splash(res):
    # Native splash logo: the same tile as the in-app BrandMark (rounded square r=0.3) at 96 of the 108 viewport.
    origin, tile = 6.0, 96.0
    r = 0.3 * tile
    x1 = origin + tile
    tile_path = (f'M{origin + r:.2f},{origin:.2f} H{x1 - r:.2f} Q{x1:.2f},{origin:.2f} {x1:.2f},{origin + r:.2f} V{x1 - r:.2f} '
                 f'Q{x1:.2f},{x1:.2f} {x1 - r:.2f},{x1:.2f} H{origin + r:.2f} Q{origin:.2f},{x1:.2f} {origin:.2f},{x1 - r:.2f} '
                 f'V{origin + r:.2f} Q{origin:.2f},{origin:.2f} {origin + r:.2f},{origin:.2f} Z')
    dots = ''.join(
        f'    <path android:fillColor="#{c[0]:02X}{c[1]:02X}{c[2]:02X}" android:pathData="{circle(origin + fx * tile, origin + fy * tile, r_ * tile)}" />\n'
        for fx, fy, r_, c in DOTS)
    open(os.path.join(res, 'drawable', 'splash_logo.xml'), 'w').write(
        '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/icons/generate_icons.py: the in-app logo tile. Do not edit by hand. -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n    android:width="96dp"\n    android:height="96dp"\n'
        '    android:viewportWidth="108"\n    android:viewportHeight="108">\n'
        f'    <path android:fillColor="#3157D5" android:pathData="{tile_path}" />\n'
        f'    <path android:fillColor="#FFFFFF" android:pathData="{glyph_path(origin, tile)}" />\n' + dots + '</vector>\n')


_font_cache = {}


def mark(size, round_=False):
    S = size * SS
    img = Image.new('RGBA', (S, S), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    if round_:
        d.ellipse([0, 0, S - 1, S - 1], fill=INDIGO)
    else:
        d.rounded_rectangle([0, 0, S - 1, S - 1], radius=S * 0.22, fill=INDIGO)
    k = 0.85 if round_ else 1.0  # keep dots inside the circle
    em = GLYPH * S * k
    font = _font_cache.setdefault(int(em), ImageFont.truetype(FONT, int(em)))
    x0 = (S - em) / 2
    d.text((x0, (S - em) / 2 + em), chr(CODEPOINT), font=font, fill=WHITE, anchor='ls')
    for fx, fy, r, c in DOTS:
        cx, cy, rr = S / 2 + (fx - 0.5) * S * k, S / 2 + (fy - 0.5) * S * k, r * S * k
        d.ellipse([cx - rr, cy - rr, cx + rr, cy + rr], fill=c)
    return img.resize((size, size), Image.LANCZOS)


root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
res = os.path.join(root, 'android', 'app', 'src', 'main', 'res')
write_vectors(res)
write_splash(res)
for name, px in {'mdpi': 48, 'hdpi': 72, 'xhdpi': 96, 'xxhdpi': 144, 'xxxhdpi': 192}.items():
    folder = os.path.join(res, f'mipmap-{name}')
    os.makedirs(folder, exist_ok=True)
    mark(px).save(os.path.join(folder, 'ic_launcher.png'))
    mark(px, round_=True).save(os.path.join(folder, 'ic_launcher_round.png'))
os.makedirs(os.path.join(root, 'assets', 'store'), exist_ok=True)
mark(512).save(os.path.join(root, 'assets', 'store', 'play_icon_512.png'))
print('icons written')
